### ISSUE TITLE
Regex exceptions should be caught and set status to UNKNOWN

### ISSUE THREAD

**Issue by kfiresmith** [Josef-Friedrich/check_systemd#18]
Hi Folks,
Very nice check.  One thing I've noticed from some testing of this check is that regex errors result in a check crash w/ traceback.

Ideally such problems would be caught within the check, and return instead the usual plugin response of `UNKNOWN` when there are problems within a check or within it's own dependencies.

Example:
```bash
/lib/nagios/plugins/check_systemd -e '*socket'
Traceback (most recent call last):
  File "/lib/nagios/plugins/check_systemd", line 724, in <module>
    main()
  File "/lib/nagios/plugins/check_systemd", line 720, in main
    check.main(args.verbose)
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 120, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python3/dist-packages/nagiosplugin/runtime.py", line 130, in execute
    self.run(check)
  File "/usr/lib/python3/dist-packages/nagiosplugin/runtime.py", line 117, in run
    check()
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 105, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 79, in _evaluate_resource
    for metric in metrics:
  File "/lib/nagios/plugins/check_systemd", line 126, in probe
    if not self.re_match(unit):
  File "/lib/nagios/plugins/check_systemd", line 66, in re_match
    if re.match(exclude, unit):
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by Josef-Friedrich** [comment]
Thank you for pointing this out. The plugin now throws a custom error message for invalid regular expressions.   
This error is then caught by the decorator `nagiosplugin.guarded` and printed out. I think the plugin should continue to return `UNKOWN` in this case.

**Comment by kfiresmith** [comment]
Thanks very much for this fix!
