### ISSUE TITLE
Timers check fails

### ISSUE THREAD

**Issue by martinrm77** [Josef-Friedrich/check_systemd#19]
Running latest stable 2.3.1
Fully patched RHEL7.9 server
When I first boot the server, the timers check fails until first time systemd-tmpfiles-clean runs.

[root@server1 plugins]# systemctl list-timers --all
```
NEXT                         LEFT      LAST PASSED UNIT                         ACTIVATES
Mon 2022-01-03 10:58:01 CET  5min left n/a  n/a    systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
n/a                          n/a       n/a  n/a    systemd-readahead-done.timer systemd-readahead-done.service

```
2 timers listed.
[root@server1 plugins]# /usr/lib64/nagios/plugins/check_systemd.py -t -W 43200 -C 86400
SYSTEMD UNKNOWN: KeyError: 'unit'
[root@server1 plugins]# /usr/lib64/nagios/plugins/check_systemd.py -t -W 43200 -C 86400 -vvv
SYSTEMD UNKNOWN: KeyError: 'unit'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "/usr/lib64/nagios/plugins/check_systemd.py", line 1272, in main
    check.main(opts.verbose)
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/runtime.py", line 131, in execute
    self.run(check)
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/local/lib/python3.6/site-packages/nagiosplugin/check.py", line 80, in _evaluate_resource
    for metric in metrics:
  File "/usr/lib64/nagios/plugins/check_systemd.py", line 730, in probe
    unit = row['unit']
KeyError: 'unit'

and after first run (ignore the start time critical):

[root@server1 plugins]# systemctl list-timers --all
```
NEXT                         LEFT     LAST                         PASSED       UNIT                         ACTIVATES
Tue 2022-01-04 10:58:02 CET  23h left Mon 2022-01-03 10:58:02 CET  1min 12s ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
n/a                          n/a      n/a                          n/a          systemd-readahead-done.timer systemd-readahead-done.service

```
2 timers listed.
[root@server1 plugins]# /usr/lib64/nagios/plugins/check_systemd.py -t -W 43200 -C 86400 -vvv
SYSTEMD CRITICAL - startup_time is 154.3 (outside range 0:120), systemd-readahead-done.timer
critical: startup_time is 154.3 (outside range 0:120)
critical: systemd-readahead-done.timer

**Comment by Josef-Friedrich** [comment]
Thank you for your excellent bug report. I hope that I could solve the bug.
